2024-08-10 17:10:31,431 INFO logging_utils Environment created successfully!
2024-08-10 17:10:32,335 INFO logging_utils Testing imports with:
2024-08-10 17:10:32,335 INFO logging_utils 	import sleap
2024-08-10 17:10:34,359 INFO logging_utils Imports passed successfully!
2024-08-10 17:10:34,360 INFO logging_utils Running user-defined test code:
"""User-defined test code to run after the imports have been tested."""

if __name__ == "__main__":
    assert False, "Replace this block with your own test code."

    # Example test code that is not run since after return
    from qtpy.QtWidgets import QApplication, QMainWindow

    def create_app():
        """Creates Qt application."""
        app = QApplication([])
        return app

    app = create_app()

    window = QMainWindow()
    window.showMaximized()

    app.exec_()

2024-08-10 17:10:34,559 ERROR logging_utils Tests failed!
Traceback (most recent call last):
  File "/Users/liezlmaree/Projects/envexp/envexp/logging_utils.py", line 114, in run_and_log
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/Users/liezlmaree/Projects/envexp/envexp/user_test_code.py", line 4, in <module>
    assert False, "Replace this block with your own test code."
AssertionError: Replace this block with your own test code.

