2024-10-02 14:34:48,096 ERROR envexp_utils.log Failed to create environment!
Traceback (most recent call last):
  File "d:\envexp\envexp\envexp_utils\log.py", line 123, in run_and_log
    raise Exception(error)
Exception
