2024-07-19 09:04:45,652 ERROR test_env Imports failed!
Traceback (most recent call last):
  File "/Users/liezlmaree/Projects/envexp/envexp/test_env.py", line 176, in test_imports
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/liezlmaree/Projects/envexp/envexp/experiment/__init__.py", line 25, in <module>
    from experiment import monitor
  File "/Users/liezlmaree/Projects/envexp/envexp/experiment/monitor.py", line 2, in <module>
    from qtpy.QtCharts import QtCharts
  File "/Users/liezlmaree/micromamba/envs/experiment/lib/python3.10/site-packages/qtpy/QtCharts.py", line 46, in <module>
    from PySide6 import QtCharts
ImportError: dlopen(/Users/liezlmaree/micromamba/envs/experiment/lib/python3.10/site-packages/PySide6/QtCharts.abi3.so, 0x0002): Library not loaded: @rpath/libQt6Charts.6.dylib
  Referenced from: <84A1A77E-8811-34B3-947D-839D30EB5D89> /Users/liezlmaree/micromamba/envs/experiment/lib/python3.10/site-packages/PySide6/QtCharts.abi3.so
  Reason: tried: '/Users/liezlmaree/micromamba/envs/experiment/lib/python3.10/site-packages/PySide6/../../../libQt6Charts.6.dylib' (no such file), '/Users/liezlmaree/micromamba/envs/experiment/lib/python3.10/site-packages/PySide6/../../../libQt6Charts.6.dylib' (no such file), '/Users/liezlmaree/micromamba/envs/experiment/bin/../lib/libQt6Charts.6.dylib' (no such file), '/Users/liezlmaree/micromamba/envs/experiment/bin/../lib/libQt6Charts.6.dylib' (no such file), '/usr/local/lib/libQt6Charts.6.dylib' (no such file), '/usr/lib/libQt6Charts.6.dylib' (no such file, not in dyld cache)

